# Generated by Django 4.1 on 2022-09-28 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 6, 8, 4, 781312, tzinfo=datetime.timezone.utc)),
        ),
    ]
